name: SaregamaApp
description: A App That Plays Sound

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  audioplayers: ^0.15.1
  double_back_to_close_app: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
     - assets/  # including all assets under assets directory

